sudo: required

services:
  - docker

env:
  - VERSION=2.8
  - VERSION=3.0
  - VERSION=3.2
  - VERSION=4.0

before_install:
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" nanobox
  - ifconfig
  - sudo -H pip install awscli

script:
  - make test-${VERSION}

jobs:
  include:
    - stage: publish
      script:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - 'if [ "$BRANCH" == "master" ]; 
            then make;
            curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token ${TRAVIS_TOKEN}" -d "{\"request\":{\"branch\":\"master\"}}" https://api.travis-ci.org/repo/nanobox-io%2Fnanobox-docker-redis/requests; 
          fi'